---
# Ubuntu related OS tasks

- name: Add an apt key by id from a keyserver
  apt_key:
    keyserver: hkps://keyserver.ubuntu.com
    id: "{{ item }}"
  with_items:
    - 7BF576066ADA65728FC7E70A8C47BE8E75BCA694

- name: install python3-certbot-nginx packages
  apt:
    name: python3-certbot-nginx
    autoremove: true
    state: latest
